### ISSUE TITLE
Using with Gradle

### ISSUE THREAD

**Issue by ISpectruM** [liquibase/liquibase-filechangelog#57]
Hi all, I`m trying to run this extension in a Spring Boot project with Gradle. Added the plugin dependency but when run the application I can see it continues to use the DB for the [DATABASECHANGELOG]. Is it possible to run it with Gradle? What kind of configurations should I make? 
Thank you!

**Comment by filipelautert** [comment]
Hello @ISpectruM - did you manage to run it with Gradle?
